services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      args:
        RUBY_VERSION: 4.0.1
        BUNDLE_WITHOUT: ""
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_TEST: rails_chat_test
      POSTGRES_DB_TEST_CACHE: rails_chat_test_cache
      POSTGRES_DB_TEST_QUEUE: rails_chat_test_queue
      POSTGRES_DB_TEST_CABLE: rails_chat_test_cable
    command: bundle exec rspec
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

volumes:
  bundle_cache:
